name: Merge gitbook branch
on:
  workflow_dispatch:
  push:
    branches:
      - gitbook

jobs:
  publish:
    name: Merge gitbook branch

    runs-on: ubuntu-latest

    steps:
    - name: Merge staging -> uat
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: gitbook
        target_branch: main
