name: Publish Retype powered website to GitHub Pages
on:
  workflow_run:
    workflows: ["Merge gitbook branch"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v2

      - uses: retypeapp/action-github-pages@v2
        with:
          update-branch: true

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: main
          branches: retype
          files: google380e3aaa82ba1c1f.html sitemap.xml
